### PR TITLE
Fix problems when running on Travis and mono

### PR DESCRIPTION
**Pull request by BeeWarloc**
Should fix the failing Travis builds.
ref https://github.com/GitTools/GitVersion/issues/1043#issuecomment-326934026

Will merge this if everything's green after.

### CODE REVIEW

**Comment by BeeWarloc** [comment]
@asbjornu Still red, seems to timeout now for some reason.. :/

Btw, do you know what this warning means?

`:  warning : WARN [09/26/17 20:36:05:28] Failed to check build server 'ContinuaCi': No access to the given key
`

**Comment by asbjornu** [comment]
The warning comes from this line:

https://github.com/GitTools/GitVersion/blob/5b6126bfea35105aa6572504278c7bf4d480ca98/src/GitVersionCore/BuildServers/BuildServerList.cs#L36

So it must be that the environment variable `ContinuaCI.Version` cannot be read for some reason? Anyway, the reason the build fails is because the NUnit tests suddenly stops. I think we can merge this and attempt to fix the NUnit tests with an upgrade of NUnit?

**Comment by asbjornu** [comment]
Ah, no. This is more likely the version of `ContinuaCI` we're running, which attempts to dig through the Windows Registry (which naturally fails on Linux):

https://github.com/GitTools/GitVersion/blob/36b9dd547d17a43b5bb7694bef8ba5819571d707/src/GitVersionCore/BuildServers/ContinuaCi.cs

**Comment by BeeWarloc** [comment]
Hmm, it's using NUnit.ConsoleRunner 3.7.0, which at the moment is the [latest published version](https://www.nuget.org/packages/NUnit.ConsoleRunner/) on nuget.org.

I might try running this on a Ubuntu 14.04 VM if I find some time for that.

**Comment by asbjornu** [comment]
Ah yes. I upgraded that in #127. 😄  A newer Ubuntu might help, yea.

**Comment by BeeWarloc** [comment]
After some investigation I've found out the exception gets thrown through [DeltaTests.cs:311](https://github.com/Pomona/Pomona/blob/e05708b809a7e632ba85d69e9c530f2cfdb1c265/tests/Pomona.UnitTests/Patch/DeltaTests.cs#L311), specifically when invocating `First` in `proxy.Children.First().Info = "Modified child";`.

What's strange is that the exception thrown is actually `null`, which explains the `NullReferenceException`. I haven't yet pinpointed the exact source of the exception, but I suspect something fishy going on with the generated proxy.

I think it's fair for NUnit (and all other code) to assume catched exceptions are not null, however since it's a testing framework and this scenarios is possible in mono they may want to have a check for it..(?)

**Comment by BeeWarloc** [comment]
@asbjornu I don't agree that CodeFactor should turn my build red for the reason it states. We can probably suppress this using some config file, but no time for that now.

Maybe the CodeFactor integration could be informational only, and not make the PRs red when they fail?

**Comment by asbjornu** [comment]
> I think it's fair for NUnit (and all other code) to assume catched exceptions are not null, however since it's a testing framework and this scenarios is possible in mono they may want to have a check for it..(?)

Yes, that's what nunit/nunit#2453 attempts to do.

> I don't agree that CodeFactor should turn my build red for the reason it states. We can probably suppress this using some config file, but no time for that now.
> Maybe the CodeFactor integration could be informational only, and not make the PRs red when they fail?

Yes, I agree that CodeFactor shouldn't fail the build. I'll have a look at the settings.

**Pull request merged**
