### PR TITLE
Replace broken test run script

### PR DESCRIPTION
**Pull request by BeeWarloc**
Now uses a bash script that can be used on all platforms.

### CODE REVIEW

**Comment by BeeWarloc** [comment]
@asbjornu Would appreciate if you could check if this works as expected on macOS too.

**Comment by asbjornu** [comment]
No [Cake](https://cakebuild.net/)? 🍰 🚫😢

**Comment by asbjornu** [comment]
But yes, that script works. It runs the different tests in succession, though. Shouldn't it be possible to run some of them in parallel?

**Comment by BeeWarloc** [comment]
Unfortunately don't have time for Cake right now, was just thinking this little script could be useful until we eventually find time to introduce something more fancy.

**Review by asbjornu — APPROVED** [review]

**Comment by BeeWarloc** [comment]
Yeah I guess they could be run in parallel some way. Don't remember if the nunit 3 console runner accepts multiple assemblies, have some vague memories that it don't.

**Comment by BeeWarloc** [comment]
Ah, changing or removing the "--workers=1" should make it parallel. Think I added that to make debugging those failures easier.

**Comment by asbjornu** [comment]
Yep, you can just feed the console runner as many assemblies as you want. :)

**Comment by BeeWarloc** [comment]
@asbjornu Pushed again with support for running in parallel.

**Pull request merged**
