### PR TITLE
Ubuntu 14.04 vagrant vm config file

### PR DESCRIPTION
**Pull request by BeeWarloc**
Along with https://github.com/Pomona/Pomona/pull/139 this should make diagnosing and fixing Travis problems easier.

### CODE REVIEW

**Comment by BeeWarloc** [comment]
Although I'm uncertain of legal issues there's a box for macOS, might want to create a vagrant config for that too. https://app.vagrantup.com/jhcook/boxes/macos-sierra

**Comment by asbjornu** [comment]
@BeeWarloc: I've tested the Vagrant config, but haven't gotten it to work. It might be the Mono installation that's failing, but the command line output isn't made available, only the exit code, so I have no idea what is actually failing.

**Comment by BeeWarloc** [comment]
I've tested the on Windows with VirtualBox, what platform are you having problems on?

**Comment by asbjornu** [comment]
I'm having problems with the OS X config, not the Linux one.

**Comment by BeeWarloc** [comment]
@asbjornu Ah, you mean [this](https://app.vagrantup.com/jhcook/boxes/macos-sierra) one?
When trying it using VirtualBox or something else?

**Comment by asbjornu** [comment]
Yes, that one. With VirtualBox. I have the start of a `VagrantFile` I can push, but it's not very important.

**Comment by BeeWarloc** [comment]
Yeah, that's definitively a "nice to have". But it would be really cool with a build task orchestrating VM's for all relevant platforms and automatically run all tests. The CI systems are great, but not very practical when debugging problems.

**Comment by asbjornu** [comment]
Indeed!

**Pull request merged**
