### PR TITLE
Make test run on R# runner (with shadow copy enabled)

### PR DESCRIPTION
**Pull request by BeeWarloc**
Had the `ClientCompatibilityTests` failing locally in the R# test runner with shadow copying setting enabled. 

This change should fix the problem; making a PR to verify that it also still passes CI test runners.

### CODE REVIEW

**Comment by asbjornu** [comment]
@BeeWarloc: Can you add `git fetch --unshallow` to `.travis.yml` as the first command in `script`? I believe that will make the currently failing GitVersion target, succeed.

**Review by asbjornu — DISMISSED** [review]
@BeeWarloc: Can you add `git fetch --unshallow` to `.travis.yml` as the first command in `script`? I believe that will make the currently failing GitVersion target, succeed.

**Comment by BeeWarloc** [comment]
@asbjornu Googled your earlier mention of that in a thread some minutes before I saw that comment. ;)  https://github.com/Pomona/Pomona/pull/132/commits/1753b5c7eaeefac283d406986eaf328abeb8a39e

I'll make an individual PR for this.

**Comment by asbjornu** [comment]
@BeeWarloc: This looks good to me now. 👍

**Pull request merged**
